### ISSUE TITLE
import gui attribute error

### ISSUE THREAD

**Issue by jsacharuk** [JStuckner/aquami#1]
Unable to import gui: 
`AttributeError: module 'matplotlib.cm' has no attribute 'spectral'`
Looks like spectral was recently removed (https://github.com/scikit-learn/scikit-learn/issues/10761). 

Would be excellent if this could be updated. Thanks!

**Comment by JStuckner** [comment]
Fixed in version 1.1.0. 
Also fixed issues with Mac.
